### PR TITLE
Create config.py

### PR DESCRIPTION
**Pull request by borusara**

### CODE REVIEW

**Comment by kokushibo17** [comment]
Ok thanks we will soon

**Comment by kokushibo17** [comment]
> _ No description provided. _

Oke

**Comment by IND-ARCH** [comment]
@kokushibo17 Abe 
Merge kr na

**Comment by kokushibo17** [comment]
@PrimexRick Karunga baad mei

**Comment by kokushibo17** [comment]
Kar kia raha hei runtime daala hee nahi tmlog run kardia

**Comment by borusara** [comment]
> Kar kia raha hei runtime daala hee nahi tmlog run kardia

kya run kia ?

**Comment by borusara** [comment]
mai pull request close kar rha

**Pull request closed without merging**
